# -*- coding: utf-8 -*-
"""address book application

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Uje255lKNgw6JTJxKBASFKQGJ4WmSp7
"""



option = ["add contact", 'delete contact', 'view contact']
print(option)
opt = int(input("Enter an option: "))

contacts = [{'name': "saurabh", 'phone number': 8445784186, 'email id': 'saurabhkumar@gmail.com'}]

if opt == 1:
    new_contact = {}
    new_contact['name'] = input("Enter a name: ")
    new_contact['phone number'] = int(input("Enter a phone number: "))
    new_contact['email id'] = input("Enter a valid email: ")
    contacts.append(new_contact)
elif opt == 2:
    contacts.pop()
elif opt == 3:
    for contact in contacts:
        print(contact)
else:
    print("Invalid option")

print("Updated contacts:", contacts)